from __future__ import annotations

from copy import deepcopy


DEFAULT_SCENARIOS = [
    {
        "scenario_name": "market_gap_down",
        "description": "Broad market opens sharply lower against long swing positions.",
        "severity": "high",
        "affected_components": ["market_regime", "portfolio_risk", "position_sizing"],
        "market_shocks": {"gap_percent": -5.0, "volatility_multiplier": 1.8},
        "data_shocks": {},
        "risk_shocks": {"risk_multiplier": 0.5, "drawdown_r": -2.0},
        "expected_behavior": {"should_reduce_risk": True, "should_block_new_trades": False, "should_return_json": True, "should_create_alert": True},
    },
    {
        "scenario_name": "market_gap_up",
        "description": "Broad market gaps higher and stresses short or underinvested assumptions.",
        "severity": "medium",
        "affected_components": ["market_regime", "short_positions"],
        "market_shocks": {"gap_percent": 4.0, "volatility_multiplier": 1.3},
        "data_shocks": {},
        "risk_shocks": {"risk_multiplier": 0.75, "drawdown_r": -0.8},
        "expected_behavior": {"should_reduce_risk": True, "should_block_new_trades": False, "should_return_json": True, "should_create_alert": False},
    },
    {
        "scenario_name": "volatility_spike",
        "description": "Volatility expands quickly, reducing position quality and raising stop risk.",
        "severity": "high",
        "affected_components": ["market_regime", "options", "position_sizing"],
        "market_shocks": {"volatility_multiplier": 2.5},
        "data_shocks": {},
        "risk_shocks": {"risk_multiplier": 0.5, "drawdown_r": -1.5},
        "expected_behavior": {"should_reduce_risk": True, "should_block_new_trades": False, "should_return_json": True, "should_create_alert": True},
    },
    {
        "scenario_name": "liquidity_crunch",
        "description": "Volume dries up and spreads widen, degrading simulated fills.",
        "severity": "high",
        "affected_components": ["liquidity", "slippage", "fill_quality"],
        "market_shocks": {"volume_multiplier": 0.35, "spread_multiplier": 3.0},
        "data_shocks": {},
        "risk_shocks": {"risk_multiplier": 0.55, "liquidity_impact": "poor"},
        "expected_behavior": {"should_reduce_risk": True, "should_block_new_trades": False, "should_return_json": True, "should_create_alert": True},
    },
    {
        "scenario_name": "correlation_spike",
        "description": "Portfolio correlations converge and concentration risk rises.",
        "severity": "high",
        "affected_components": ["correlation", "concentration"],
        "market_shocks": {"correlation": 0.95},
        "data_shocks": {},
        "risk_shocks": {"risk_multiplier": 0.6, "drawdown_r": -1.2},
        "expected_behavior": {"should_reduce_risk": True, "should_block_new_trades": False, "should_return_json": True, "should_create_alert": True},
    },
    {
        "scenario_name": "sector_selloff",
        "description": "A concentrated sector sells off faster than the market.",
        "severity": "high",
        "affected_components": ["sector_exposure", "concentration"],
        "market_shocks": {"sector_gap_percent": -7.0},
        "data_shocks": {},
        "risk_shocks": {"risk_multiplier": 0.55, "drawdown_r": -1.8},
        "expected_behavior": {"should_reduce_risk": True, "should_block_new_trades": False, "should_return_json": True, "should_create_alert": True},
    },
    {
        "scenario_name": "macro_critical_event",
        "description": "Critical macro event window should block new simulated trades.",
        "severity": "extreme",
        "affected_components": ["macro_risk", "trading_brain"],
        "market_shocks": {"volatility_multiplier": 2.0},
        "data_shocks": {},
        "risk_shocks": {"risk_multiplier": 0.0, "drawdown_r": -2.0},
        "expected_behavior": {"should_reduce_risk": True, "should_block_new_trades": True, "should_return_json": True, "should_create_alert": True},
    },
    {
        "scenario_name": "bad_data_stale_prices",
        "description": "Market data is stale enough to block final recommendations.",
        "severity": "extreme",
        "affected_components": ["market_data", "data_quality"],
        "market_shocks": {},
        "data_shocks": {"stale_days": 5, "quality_label": "stale"},
        "risk_shocks": {"risk_multiplier": 0.0, "data_quality_impact": "stale"},
        "expected_behavior": {"should_reduce_risk": True, "should_block_new_trades": True, "should_return_json": True, "should_create_alert": True},
    },
    {
        "scenario_name": "provider_outage",
        "description": "Primary market-data provider is unavailable.",
        "severity": "extreme",
        "affected_components": ["market_data", "provider_routing"],
        "market_shocks": {},
        "data_shocks": {"provider_status": "unavailable"},
        "risk_shocks": {"risk_multiplier": 0.0, "data_quality_impact": "unavailable"},
        "expected_behavior": {"should_reduce_risk": True, "should_block_new_trades": True, "should_return_json": True, "should_create_alert": True},
    },
    {
        "scenario_name": "partial_scan_timeout",
        "description": "Scanner returns partial results after timeout.",
        "severity": "medium",
        "affected_components": ["async_scanner", "data_quality"],
        "market_shocks": {},
        "data_shocks": {"partial_results_used": True, "timeout_fraction": 0.4},
        "risk_shocks": {"risk_multiplier": 0.75},
        "expected_behavior": {"should_reduce_risk": True, "should_block_new_trades": False, "should_return_json": True, "should_create_alert": False},
    },
    {
        "scenario_name": "slippage_widening",
        "description": "Paper fill slippage expands beyond normal assumptions.",
        "severity": "high",
        "affected_components": ["slippage", "paper_fill"],
        "market_shocks": {"spread_multiplier": 2.5},
        "data_shocks": {},
        "risk_shocks": {"risk_multiplier": 0.65, "liquidity_impact": "poor"},
        "expected_behavior": {"should_reduce_risk": True, "should_block_new_trades": False, "should_return_json": True, "should_create_alert": True},
    },
    {
        "scenario_name": "news_or_filing_shock",
        "description": "Adverse headline or filing shock should block affected candidates.",
        "severity": "extreme",
        "affected_components": ["news", "sec_filings", "research_risk"],
        "market_shocks": {},
        "data_shocks": {"headline_risk_level": "critical"},
        "risk_shocks": {"risk_multiplier": 0.0},
        "expected_behavior": {"should_reduce_risk": True, "should_block_new_trades": True, "should_return_json": True, "should_create_alert": True},
    },
    {
        "scenario_name": "circuit_breaker_loss_streak",
        "description": "Recent loss streak should block or sharply reduce new simulated risk.",
        "severity": "extreme",
        "affected_components": ["circuit_breaker", "performance"],
        "market_shocks": {},
        "data_shocks": {},
        "risk_shocks": {"risk_multiplier": 0.0, "loss_streak": 5},
        "expected_behavior": {"should_reduce_risk": True, "should_block_new_trades": True, "should_return_json": True, "should_create_alert": True},
    },
    {
        "scenario_name": "options_iv_spike",
        "description": "Options implied volatility spikes; options remain gated unless approved.",
        "severity": "high",
        "affected_components": ["options", "iv_rank"],
        "market_shocks": {"iv_multiplier": 2.0},
        "data_shocks": {},
        "risk_shocks": {"risk_multiplier": 0.7},
        "expected_behavior": {"should_reduce_risk": True, "should_block_new_trades": False, "should_return_json": True, "should_create_alert": False},
    },
    {
        "scenario_name": "options_bid_ask_widening",
        "description": "Options spreads widen, keeping options research-only or blocked.",
        "severity": "high",
        "affected_components": ["options", "fill_quality"],
        "market_shocks": {"spread_multiplier": 4.0},
        "data_shocks": {},
        "risk_shocks": {"risk_multiplier": 0.7, "liquidity_impact": "poor"},
        "expected_behavior": {"should_reduce_risk": True, "should_block_new_trades": False, "should_return_json": True, "should_create_alert": False},
    },
    {
        "scenario_name": "memory_contradiction",
        "description": "Optional memory contradicts the setup; decision support should be ignored or downgraded.",
        "severity": "medium",
        "affected_components": ["memory", "retrieval_quality"],
        "market_shocks": {},
        "data_shocks": {"memory_quality": "contradictory"},
        "risk_shocks": {"risk_multiplier": 0.8},
        "expected_behavior": {"should_reduce_risk": True, "should_block_new_trades": False, "should_return_json": True, "should_create_alert": False},
    },
    {
        "scenario_name": "audit_chain_failure_simulated",
        "description": "Simulated audit-chain failure should be detected without mutating the real audit log.",
        "severity": "extreme",
        "affected_components": ["audit_log"],
        "market_shocks": {},
        "data_shocks": {"audit_chain_ok": False},
        "risk_shocks": {"risk_multiplier": 1.0},
        "expected_behavior": {"should_reduce_risk": False, "should_block_new_trades": False, "should_return_json": True, "should_create_alert": True},
    },
    {
        "scenario_name": "schema_validation_failure_simulated",
        "description": "Simulated schema validation failure should be surfaced as critical diagnostics.",
        "severity": "extreme",
        "affected_components": ["schema_validation"],
        "market_shocks": {},
        "data_shocks": {"schema_ok": False},
        "risk_shocks": {"risk_multiplier": 1.0},
        "expected_behavior": {"should_reduce_risk": False, "should_block_new_trades": False, "should_return_json": True, "should_create_alert": True},
    },
]


def list_stress_scenarios(config: dict | None = None) -> dict:
    scenarios = deepcopy(DEFAULT_SCENARIOS)
    return {
        "ok": True,
        "scenario_count": len(scenarios),
        "scenarios": scenarios,
        "warnings": [],
        "errors": [],
    }


def get_stress_scenario(
    scenario_name: str,
    config: dict | None = None,
) -> dict:
    normalized = str(scenario_name or "").strip().lower()
    for scenario in DEFAULT_SCENARIOS:
        if scenario["scenario_name"] == normalized:
            return {"ok": True, "scenario": deepcopy(scenario), "warnings": [], "errors": []}
    return {
        "ok": False,
        "scenario": None,
        "warnings": [],
        "errors": [f"Stress scenario not found: {scenario_name}"],
    }
